### ISSUE TITLE
Bing Webmaster Tools does not support HTTPS SNI

### ISSUE THREAD

**Issue by tkrotoff** [tkrotoff/osteo15.com#16]
Mail sent to [Bing Webmaster support](https://support.discoverbing.com/eform.aspx?productKey=bingwebmaster&ct=eformts), 2015/03/12:

> I have a HTTPS website https://osteo15.com/ that is using SNI, see http://en.wikipedia.org/wiki/Server_Name_Indication
> 
> ~~Bing does not index the pages and~~ Bing Webmaster Tools is not capable to read the sitemap https://osteo15.com/sitemap.xml
> When I try to use "Fetch as Bingbot" it says "URL:  https://osteo15.com/ Status:  Unexpected Error".
> 
> Of course everything works fine with Google Webmaster Tools and the website gets indexed by Google.
> 
> I conclude that Bing does not support SNI, do you confirm this? If yes then when do you expect to support SNI?

Support Ticket Number: 1282830133

**Comment by tkrotoff** [comment]
Snip Microsoft Support bullshit.

2015/03/12:

> Again
> - My robots.txt is fine
> - I'm hosting my website on Amazon S3 and they don't block any robot, FYI they power probably half of the Silicon Valley companies
> - Google ~~and Yandex~~ webmaster tools don't have any problem
> - The only "special" thing about my website is that I'm using Server Name Indication - SNI (http://en.wikipedia.org/wiki/Server_Name_Indication) for HTTPS
> 
> And I think I got my answer using a simple test: I've enabled HTTP temporary, guess the result with "Fetch as Bingbot"...
> https://osteo15.com => "Status: One or more fetch attempts were performed but they failed." (Previously I got "Status: Unexpected Error")
> http://osteo15.com => "Status: Completed"
> 
> Check the screenshots.
> 
> So the simple question from my first email still stands: "I conclude that Bing [Webmaster Tools?] does not support SNI, do you confirm this? If yes then when do you expect to support SNI?"

2015/03/16:

> I've tested just now and it seems to work:
> URL:  https://osteo15.com/   Status:  Completed

2015/03/17:

> The problem is more subtil than just GET https://osteo15.com 200 OK: the sitemap (https://osteo15.com/sitemap.xml) fails to be fetched by Bing Webmaster Tools :/

**Comment by tkrotoff** [comment]
2015/03/17:

```
The problem is more subtil than just GET https://osteo15.com 200 OK: the sitemap (https://osteo15.com/sitemap.xml) fails to be fetched by Bing Webmaster Tools :/
```

**Comment by tkrotoff** [comment]
2015/03/19 Microsoft Support bullshit again:

> Hello Tanguy,
> Thank you for informing us about the new development of the status of your site. With regard to the error in submission of your sitemap, please be informed that this is apparently a **server issue which could be addressed by your web host provider**.  We encourage you to contact your web host provider to deal with this issue.
> Thank you for your remarkable patience.  Have a nice day.
> Sincerely,
> Dennis
> Bing Technical Support

**Comment by ghost** [comment]
Same issue for me. I also use SNI for my websites. Let's see what they are going to do...

> Hello Dennis,
> 
> My name is Mark from Bing Technical Support and I will be assisting you with your Service Request.
> 
> We will forward this to our research department to re-evaluate your website and sitemap. We understand how important this is for you and we appreciate your continued patience as we endeavor to resolve this matter. We'll provide you with updates as they become available. 
> 
> Thank you for contacting and have a great day.
> 
> Sincerely,
> 
> Mark
> Bing Technical Support

**Comment by ghost** [comment]
I have been emailing with Bing support for several weeks now and as of today, they started to offer limited support for SNI. 

I made clear to them that the issue was 100% sure in their lack of SNI support by moving one of my websites to a dedicated IPv4 and turning off SNI for that address. After that, the sitemap got succesfully verified by Bing. All other HTTPS websites/sitemaps that are on the same server, but on the shared IPv4 address, were not indexed. Seems like they finally started implementing SNI!

> We highly appreciate your patience as we review this matter together with our Product Group. My name is Jenny and I will be providing you with the status of this Service Request.
> 
> We would like to inform you that as of today, Bing only supports a limited number of SNI websites through a whitelist. We understand that more and more websites are switching to SNI so we plan to expand our support for all SNI hosts in the next 6 months.
> 
> As a short term mitigation, we can whitelist about 10 - 20 SNI hosts for you, if needed.

So if you would like to have your SNI website added to the whitelist, I'd recommend [sending Bing Support an email](https://support.microsoft.com/en-us/getsupport?oaspworkflow=start_1.0.0.0&wfname=capsub&productkey=BingWebmaster&locale=en-us&ccsid=635653401511568273) so that your SNI websites will be succesfully indexed.

**Comment by tkrotoff** [comment]
Thanks @DennisAm for your researches. I'm done wasting time talking with MS support: it's not like Bing is an absolute necessity :) I'll simply wait.

**Comment by JScharloo** [comment]
Too bad that BWMT isn't clear on the issue. Precious development time is lost whilst researching said issues. Maybe it'd be a quickfix to allow Bingbot and sitemap parsers to display a clear error message, for the time being.

**Comment by jesim** [comment]
Thanks for making this issue with Bing known.

In my experience, a whitelisted SNI website does not extend to sitemap parsing (i.e. submission of a HTTPS sitemap via Bing Webmaster Tools), which was confirmed by Microsoft Support:

> This is Mookie of Bing Technical Support and I'll be updating you on your sitemap submission concern.
> 
> We appreciate the patience you've put forth on this matter. After further review, we would like to inform you that although your site had been whitelisted on SNI the current sitemap fetcher doesn't support SNI which is the reason the submission fails. As a workaround, we suggest submitting your sitemap that is hosted on HTTP.
> 
> We apologize for any inconvenience this may have caused. Rest assured that the Bing Webmaster Tools development team is working continuously to improve the feature's performance and include the feature on future updates of the program.

**Comment by tkrotoff** [comment]
Someone posted this on [Hacker News](https://news.ycombinator.com/item?id=9545169) and [Reddit](https://www.reddit.com/r/ssl/comments/366faf/bing_webmaster_tools_does_not_support_https_sni/) :)

**Comment by brucee07** [comment]
@tkrotoff @DennisAm Hello guys. I am also facing the same issue with my https website ever since we have migrated from http to https. Can you please share if your issue is fixed by Bing support since I am not getting any response from their side.

**Comment by oxycoder** [comment]
Contact them today and got a reply:

> We expect the Sitemap fetcher to be updated to the latest standards this fall, but as a workaround for missing support for Sitemaps on SNI, the site owner can either temporarily
> a) serve the Sitemap over http:// or
> b) host the sitemaps on a non-SNI server.

So as they expected, they will update it at this fall :dancers:

**Comment by ghost** [comment]
@oxycoder Thanks for the update! We'll see what happens :smile:

**Comment by dhaupin** [comment]
@Microsoft I know you have seen this thread. Since this is the only post on the matter anywhere on the internet, I say my piece to you:

**_What is the holdup?!?!?!**_ SNI has been around since before 2006 which is 10 years of maturity. Millions of sites use it. Most SaaS use it. MS itself is reinforcing it. Its mind blowing that a _tech company_ that tries to _drive the web_ has such immature nievity when it comes to actual execution. This is a fact: you can't support modern web and have never been able to because you think you know best. Well, that is false, boys. You don't know best. MS is always running behind by miles, dropping the large ball since the 90's trying to catch up with real standards. Get your shhh together and stop being such f'tards about everything you do with your cheesy company. You're losing credibility day by day, but i know you don't care. Just fix the Bingbot, end of story, simple.

**Comment by peterromfeldhk** [comment]
Still facing the Issue :/

**Comment by janneman001** [comment]
Yep, here too. Such arrogance. I thought we would be updated on the matter......

**Comment by YoavRheims** [comment]
Still no solution... same issue with all HTTPS websites.

**Comment by dhaupin** [comment]
@Microsoft Still lagging on the fix eh? Bingbot is hitting the SSL-SNI sitemaps, make it work in BWT please...what is the holdup?

2016-05-02 19:23:50 @Sitemap example.com | Google Sitemap was generated via IP 40.77.167.83 [Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)] Memory: 19.5MB Time: 0 Sec

2016-05-02 14:53:26 @Sitemap example.com | Google Sitemap was generated via IP 157.55.39.152 [Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)] Memory: 19.5MB Time: 0 Sec

2016-04-30 10:25:17 @Sitemap example.com | Google Sitemap was generated via IP 40.77.167.46 [Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)] Memory: 19.25MB Time: 6.22 Sec

2016-04-29 17:24:20 @Sitemap example.com | Google Sitemap was generated via IP 207.46.13.125 [Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)] Memory: 16.5MB Time: 0 Sec

2016-04-29 16:01:18 @Sitemap example.com | Google Sitemap was generated via IP 157.55.39.72 [Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)] Memory: 19.25MB Time: 7.06 Sec

**Comment by damianetienne** [comment]
Seems to have been resolved (at least in my case) . All my sitemaps now appear correctly .

**Comment by dhaupin** [comment]
@damianetienne confirmed, it's working on this end too. Finally :) Thanks @microsoft

**Comment by multistarmedia** [comment]
This is not fully solved.  Still getting this issue.  Here is Microsoft's Bullshit answer this time.

Hi XXXX,

Thank you for contacting Bing Webmaster Support. I reviewed your issue and we do see this from time to time and because there are so many possible points of failure that is neither on our site or yours and more a chain of servers outside MSFT/client that figure out the naming>ip mapping it is really hard to pin point.

Usually, since it's a latency and we normally just resubmit the site map until it goes thru. I just submitted and will monitor it from here. I can take up to 8 hours to go thru.

If you continue to see DNS Failure, then you may need to get your network admin involved to review the issue on your end

Please verify that this information is complete. If you have any follow-up questions, please let me know as soon as possible.

Please take a moment to give us feedback on the service we provided:
Robert | TECHNICAL SUPPORT ENGINEER 
Bing Support | Supporting your needs 24 x 7.
Bing Ads - Check Out What's New in the Latest Release!

F'kin Microsoft.

**Comment by tkrotoff** [comment]
It's working (and has been for quite some time now I think):
- "Fetch as Bingbot" returns "Completed"
- Sitemap https://osteo15.com/sitemap.xml returns "Success"
- The dashboard informations are OK
